apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: activemq
  name: activemq
spec:
  ports:
  - name: "61616"
    port: 61616
    targetPort: 61616
  selector:
    service: activemq
status:
  loadBalancer: {}
