apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
    labels:
      service: activemq
    name: activemq
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: activemq
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: activemq
      spec:
        containers:
        - env:
          - name: ACTIVEMQ_ADMIN_PASSWORD
            value: '""'
          - name: ACTIVEMQ_ADMIN_LOGIN
            value: '""'
          image: webcenter/activemq:5.14.3
          imagePullPolicy: IfNotPresent
          name: activemq
          ports:
          - containerPort: 61616
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    generation: 1
    labels:
      service: logic-admin
    name: logic-admin
    namespace: default
    resourceVersion: "23215"
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: logic-admin
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: logic-admin
      spec:
        containers:
        - env:
          - name: NG_MYSQL_URL
            value: jdbc:mysql://mysql:3306
          - name: NG_MYSQL_USER_NAME
            value: root
          - name: NG_MYSQL_PASSWORD
            value: password
          - name: NG_ACTIVEMQ_URL
            value: failover:(tcp://activemqurl:61616)
          - name: NG_PROCCESING_URL
            value: http://logic-processing:8080/processing
          image: eu.gcr.io/anakatech/logic-admin:release-0.0.3-291
          imagePullPolicy: IfNotPresent
          name: logic-admin
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
    generation: 1
    labels:
      service: logic-admin-ui
    name: logic-admin-ui
    namespace: default
    resourceVersion: "23204"
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: logic-admin-ui
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: logic-admin-ui
      spec:
        containers:
        - image: eu.gcr.io/anakatech/admin-client:latest
          imagePullPolicy: Always
          name: logic-admin-ui
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
    generation: 1
    labels:
      service: logic-game
    name: logic-game
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: logic-game
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: logic-game
      spec:
        containers:
        - env:
          - name: NG_MYSQL_URL
            value: jdbc:mysql://mysql:3306
          - name: NG_MYSQL_USER_NAME
            value: root
          - name: NG_MYSQL_PASSWORD
            value: password
          - name: NG_ACTIVEMQ_URL
            value: failover:(tcp://activemqurl:61616)
          image: eu.gcr.io/anakatech/logic-game:release-3.0.0-144
          imagePullPolicy: IfNotPresent
          name: logic-game
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
    generation: 1
    labels:
      service: logic-player
    name: logic-player
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: logic-player
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: logic-player
      spec:
        containers:
        - env:
          - name: NG_PROCCESING_URL
            value: http://logic-processing:8080/processing
          - name: NG_MYSQL_URL
            value: jdbc:mysql://mysql:3306
          - name: NG_MYSQL_USER_NAME
            value: root
          - name: NG_MYSQL_PASSWORD
            value: password
          - name: NG_ACTIVEMQ_URL
            value: failover:(tcp://activemqurl:61616)
          image: eu.gcr.io/anakatech/logic-player:release-0.0.3-684
          imagePullPolicy: IfNotPresent
          name: logic-player
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: 2017-03-28T11:28:59Z
    generation: 1
    labels:
      service: logic-processing
    name: logic-processing
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: logic-processing
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: logic-processing
      spec:
        containers:
        - env:
          - name: NG_MYSQL_URL
            value: jdbc:mysql://mysql:3306
          - name: NG_MYSQL_USER_NAME
            value: root
          - name: NG_MYSQL_PASSWORD
            value: password
          image: eu.gcr.io/anakatech/logic-processing:release-0.0.3-114
          imagePullPolicy: IfNotPresent
          name: logic-processing
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
    generation: 1
    labels:
      service: mysql
    name: mysql
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: mysql
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: mysql
      spec:
        containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          image: eu.gcr.io/anakatech/mysql-qa:1.0.0
          imagePullPolicy: Always
          name: mysql
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
    generation: 1
    labels:
      service: ng-client
    name: ng-client
    namespace: default
    resourceVersion: "23286"
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: ng-client
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: ng-client
      spec:
        containers:
        - env:
          - name: NODE_ENV
            value: QA
          image: eu.gcr.io/anakatech/ng-client:3254
          imagePullPolicy: IfNotPresent
          name: ng-client
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: nginx
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: nginx
      spec:
        containers:
        - image: nginx:alpine
          name: nginx
          ports:
          - containerPort: 80
          resources: {}
  status: {}
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
