apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: logic-game
  name: logic-game
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: logic-game
status:
  loadBalancer: {}
