apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: logic-processing
  name: logic-processing
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: logic-processing
status:
  loadBalancer: {}
