apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: logic-player
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: logic-player
    spec:
      containers:
      - env:
        - name: NG_PROCCESING_URL
          value: http://logic-processing:8080/processing
        - name: NG_MYSQL_URL
          value: jdbc:mysql://mysql:3306
        - name: NG_MYSQL_USER_NAME
          value: root
        - name: NG_MYSQL_PASSWORD
          value: password
        - name: NG_ACTIVEMQ_URL
          value: failover:(tcp://activemqurl:61616)
        image: eu.gcr.io/anakatech/logic-player:release-0.0.3-684
        name: logic-player
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
