apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: logic-player
  name: logic-player
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8080
  selector:
    service: logic-player
status:
  loadBalancer: {}
