apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: logic-admin
  name: logic-admin
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: logic-admin
status:
  loadBalancer: {}
