apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: logic-admin
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: logic-admin
    spec:
      containers:
      - env:
        - name: NG_MYSQL_URL
          value: jdbc:mysql://mysql:3306
        - name: NG_MYSQL_USER_NAME
          value: root
        - name: NG_MYSQL_PASSWORD
          value: password
        - name: NG_ACTIVEMQ_URL
          value: failover:(tcp://activemqurl:61616)
        - name: NG_PROCCESING_URL
          value: http://logic-processing:8080/processing
        image: eu.gcr.io/anakatech/logic-admin:release-0.0.3-291
        name: logic-admin
        resources: {}
      restartPolicy: Always
status: {}
