apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: logic-admin-ui
  name: logic-admin-ui
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: logic-admin-ui
status:
  loadBalancer: {}
