apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: ng-client
  name: ng-client
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: ng-client
status:
  loadBalancer: {}
